create table if not exists public.stock (
  id bigint generated by default as identity primary key,
  name text not null,
  status text not null default 'available' check (status in ('available', 'low_stock', 'unavailable')),
  quantity text,
  unit text,
  grade text,
  icon text,
  display_order integer not null default 0,
  updated_at timestamptz not null default now()
);

alter table public.stock enable row level security;

drop policy if exists "Anyone can view stock" on public.stock;
create policy "Anyone can view stock" on public.stock for select to anon using (true);

insert into public.stock (name, status, quantity, unit, grade, icon, display_order) values
('Maize', 'available', 'Ask for quantity', '50 kg bags', 'Quality grain', '🌽', 1),
('Groundnuts', 'available', 'Ask for quantity', 'kg / bags', 'Selected nuts', '🥜', 2),
('Beans', 'low_stock', 'Limited', 'kg / bags', 'Cleaned beans', '🫘', 3),
('Soybeans', 'available', 'Ask for quantity', '50 kg bags', 'Quality grain', '🌱', 4),
('Rice', 'available', 'Ask for quantity', 'kg / bags', 'Cleaned rice', '🍚', 5),
('Sunflower', 'unavailable', 'Out of stock', '50 kg bags', 'Oil seed', '🌻', 6);
